# Generated by Django 2.1.3 on 2018-12-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test1', '0003_testmodel_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='delete',
            new_name='active',
        ),
    ]
