# Generated by Django 2.1.3 on 2020-04-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test1', '0004_auto_20181206_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='testMate',
            new_name='apellido_materno',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='testName',
            new_name='apellido_paterno',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='testPate',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
